### ISSUE TITLE
Compatibility with Python 2.7

### ISSUE THREAD

**Issue by xz-ding** [JinyuanSun/PymolFold#1]
Nice work, Jinyuan! 

I was trying to run the script on in PyMOL v2.3.3 (installed with Schrodinger's .dmg on MacOS 10.14.6), but ran into some compatibility issue. It appears that the Python API that comes with this version of PyMOL is using Python 2.7 by default.  It would be awesome if the script can be made backward compatible. Thanks!

Here is the error message:

Traceback (most recent call last):
  File "/Applications/PyMOL.app/Contents/lib/python2.7/site-packages/pymol/parsing.py", line 483, in run
    run_(path, ns_pymol, ns_pymol)
  File "/Applications/PyMOL.app/Contents/lib/python2.7/site-packages/pymol/parsing.py", line 532, in run_file
    execfile(file,global_ns,local_ns)
  File "/Applications/PyMOL.app/Contents/lib/python2.7/site-packages/pymol/parsing.py", line 526, in execfile
    co = compile(pi.file_read(filename), filename, 'exec')
  File "https://raw.githubusercontent.com/JinyuanSun/PymolFold/main/predict_structure.py", line 9
    def query_esmfold(sequence:str, name:str=None):
                              ^
SyntaxError: invalid syntax

**Comment by JinyuanSun** [comment]
Sure, but I don't have a python2 env, would you like to help me test it? Should be easy.

**Comment by xz-ding** [comment]
Sure! Happy to do it

**Comment by JinyuanSun** [comment]
You may try this to install the version that might be compatible with python2 and pymol2.3:
```
run https://raw.githubusercontent.com/JinyuanSun/PymolFold/py27/predict_structure.py
```
Let me know if this works.

**Comment by xz-ding** [comment]
Thanks Jinyuan! This version works, mostly. When I try modeling a short peptide (<6aa), it seems to work like a charm. But when the peptide is longer than 6aa, it returns some "INTERNAL SERVER ERROR". I'm not sure if this is still an issue with the pymol script or this is an error from the ESMfold server.

For example, here are two running results with a longer peptide and a shorter peptide, respectively (I've tested a few other peptides and the pattern seems to be consistent):

# Testing with a 11aa peptide
PyMOL>esmfold TESTRANTEST
INTERNAL SERVER ERROR
 Error: failed to open file "/Users/xiaozhe/test_pymolfold/TESEST.pdb"

# Testing with a 4aa peptide
PyMOL>esmfold TEST
Results saved to /Users/xiaozhe/test_pymolfold/TESEST.pdb

**Comment by JinyuanSun** [comment]
I ran into `INTERNAL SERVER ERROR` once, but now it's back to normal and I am not sure what went wrong.  
Maybe try this again? And make sure you have the `requests` installed (can be installed with `pip install requests` in the terminal).

**Comment by xz-ding** [comment]
I played with multiple sequences and found that the occurrence of  "INTERNAL SERVER ERROR" is stochastic, and the probability of getting the error becomes higher when you have a longer sequence.  However, if I repeat the exact same request a few times, I'll eventually get a successful run...

I guess there is some stability issue in the current version of ESMfold API (or maybe they made it intentionally to block abuse of the service).

**Comment by JinyuanSun** [comment]
OK. I am going to close this one. If any further problem occurs, feel free to reopen it or open a new one.
