### ISSUE TITLE
Obtaining pLDDT values for predicted structure

### ISSUE THREAD

**Issue by biotech70** [JinyuanSun/PymolFold#3]
Is it possible to calculate the value of pLDDT for the predicted structures in PymolFold?

**Comment by JinyuanSun** [comment]
The pLDDT is labeled in the b-factor column in the pdb file returned from the ESMFold API.  
To get the plddt, you may use `biopython` or `biotite`:
```python
# biotite example
import biotite.structure.io as bsio
struct = bsio.load_structure("/path/to/test.pdb", extra_fields=["b_factor"])
pLDDT = struct[struct.atom_name == 'CA'].b_factor.mean()
```
I guess it will be great to print pLDDT in the pymol console.  I will try to avoid the dependency to make it easy to run.

**Comment by JinyuanSun** [comment]
Try the updated version.  
Also, feel free to reopen it or open a new issue if feel needed.
