### ISSUE TITLE
num_recycles in PymolFold

### ISSUE THREAD

**Issue by biotech70** [JinyuanSun/PymolFold#5]
How can the num_recycles be adjusted to 24 in PymolFold?

**Comment by JinyuanSun** [comment]
As far as I know, the API provided by Meta does not support this, check the [ESMFold_colab](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/beta/ESMFold.ipynb) please. In the notebook, you are free to change the recycle number as you like.

**Comment by biotech70** [comment]
Yes, I know that this parameter is adjustable in ESMfold, but I will hope this parameter add to PymolFold.

**Comment by JinyuanSun** [comment]
Sorry, I do not have the resource to host a new API.  
I will leave this issue open to see if anyone has a good solution.

**Comment by JinyuanSun** [comment]
@biotech70 Hi, check the updates. We have a self-hosted API and support user-defined num_recycles.
